docs: echo warning when commit is too long

diff --git a/.hooks/commit-msg b/.hooks/commit-msg
--- a/.hooks/commit-msg
+++ b/.hooks/commit-msg
@@ -1,9 +1,12 @@
 #!/bin/bash 
 
+# first (and only) argument is whether we abort commit or not
 print_help() {
-    echo -e "Aborting commit. Your commit message does not follow the Conventional Commits specification." >&2
+    if $1; then
+        echo -e "Aborting commit. Your commit message does not follow the Conventional Commits specification.\n" >&2
+    fi
 
-    echo -e "\nCommit message structure: \n" >&2
+    echo -e "Commit message structure: \n" >&2
 
     echo -e "\t<type>[(<optional scope>)]: <description>" >&2
 
@@ -33,13 +36,11 @@ print_help() {
 
 if ! head -1 "$1" | grep -qE "^(feat|fix|ci|build|chore|docs|test|style|refactor|perf|revert)(\(.+?\))?: .{1,}$"; then
     echo -e "ERROR: Given commit type is wrong!\n" >&2
-    print_help
+    print_help true
 
     exit 1
 fi
 if ! head -1 "$1" | grep -qE "^.{1,50}$"; then
-    echo -e "ERROR: '<type>[(<optional scope>)]: <description>' must not have more than 50 characters!\n" >&2
-    print_help
-
-    exit 1
+    echo -e "WARNING: '<type>[(<optional scope>)]: <description>' should not have more than 50 characters!\n" >&2
+    print_help false
 fi
